export const levaTheme = {
  colors: {
    elevation1: "#0a0a0a",
    elevation2: "#000000",
    elevation3: "#484848",
    accent1: "#ffffff",
    accent2: "#484848",
    accent3: "#ffffff",
    highlight1: "#ffffff",
    highlight2: "#ffffff",
    highlight3: "#fefefe",
    vivid1: "#ffffff",
  },
  radii: {
    xs: "0px",
    sm: "px",
    lg: "0px",
  },
  space: {
    sm: "6px",
    md: "12px",
    rowGap: "8px",
    colGap: "8px",
  },
  fontSizes: {
    root: "11px",
  },
  sizes: {
    rootWidth: "280px",
    controlWidth: "160px",
    scrubberWidth: "8px",
    scrubberHeight: "16px",
    rowHeight: "26px",
    folderHeight: "20px",
    checkboxSize: "16px",
    joystickWidth: "100px",
    joystickHeight: "100px",
    colorPickerWidth: "160px",
    colorPickerHeight: "100px",
    monitorHeight: "60px",
    titleBarHeight: "39px",
  },
  borderWidths: {
    root: "0px",
    input: "1px",
    focus: "1px",
    hover: "1px",
    active: "1px",
    folder: "1px",
  },
  fontWeights: {
    label: "light",
    folder: "normal",
    button: "normal",
  },
};
